### ISSUE TITLE
Transfert des packages sur l'organisation Yunohost-Apps

### ISSUE THREAD

**Issue by a1ex4** [YunoHost-Apps/headphones_ynh#2]
Salut, les packages Yunohost ont été déplacés dans l'organisation [Yunohost-Apps](https://github.com/YunoHost-Apps), pourrais tu faire un transfert d'ownership à l'organisation ? De cette manière, plusieurs personnes peuvent bosser sur une app de manière centralisée. Merci!

**Comment by Snipees** [comment]
Hello, aucun souci mais le transfert ne peut se faire que dans une organisation dans laquelle j'ai les droits admins, me semble-t-il (cf. "Transfer this repository to another user or to an organization where you have admin rights.")

J'ai bien essayé, mais ca ne fonctionne pas tel quel.

**Comment by M5oul** [comment]
Invitation envoyée pour rejoindre l’organisation.

**Comment by Snipees** [comment]
Merci ;)

Voilà qui est fait !
